services:
  - type: web
    name: Cloud-Nest
    env: node
    plan: free   # ✅ Free Instance (you can upgrade later if needed)
    rootDir: ./backend
    buildCommand: |
      # Build frontend
      cd ../frontend && npm install && npm run build
      # Install backend dependencies
      cd ../backend && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false   # set manually in Render Dashboard
      - key: JWT_SECRET
        sync: false   # set manually in Render Dashboard
