services:
  - type: web
    name: caffora-app
    env: node
    rootDir: ./backend
    buildCommand: |
      cd ../frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false # you’ll set this in Render dashboard
    